#!/bin/bash

if [ "$(uname -m)" = "x86_64" ]; then
   SLACKWARE=/mnt/d/slackware/slackware64-current/slackware64/
   TRUVA=/mnt/sdb1/packages/64bit
else
   SLACKWARE=/cdrom/slackware/
   TRUVA=/mnt/sdb1/packages/32bit
fi

LIVEKIT=/mnt/sdb1/linux-live
EMPTY=/tmp/truva-empty
UNION=/hedef

#-- umount $UNION 2>/dev/null
#-- rm -Rf $UNION
mkdir -p $UNION

#-- umount $EMPTY 2>/dev/null
#-- rm -Rf $EMPTY
mkdir -p $EMPTY

# Install pakcage from Slackware pkg tree
# $1 = package name to install
# $2 = source tree to search for package
# $3 = target root
#
sinstall()
{
   local PKG
   PKG="$(find "$2" | egrep "/$1-[^-]+-[^-]+-[^-]+[.]t[gx]z\$" | head -n 1)"

   if [ "$PKG" = "" ]; then
      echo -ne "\\nError! Package $1 not found!\\n"
   else
      echo Installing $PKG
      installpkg -root "$3" "$PKG" >/dev/null
   fi
}

# change union target storage to $1
# work on union mount $2
#

union_target_set()
{
   rm -Rf "$1"
   mkdir -p "$1"
#    mount -o remount,mod:$(cat /sys/fs/aufs/*/br0 | sed -r "s/=.*//")=ro none "$2" 2>/dev/null
#    mount -o remount,add:0:"$1" none "$2"
}

# install all packages for bundles


for i in $(ls -1 bundles | sort); do
   union_target_set /tmp/$i "$UNION"

   cat ./bundles/$i/pkglist | while read LINE; do
      SRC="$(echo "$LINE" | cut -d: -f 1)"
      PKG="$(echo "$LINE" | cut -d: -f 2)"

      if [ "$SRC" = "slackware" ]; then
         sinstall "$PKG" "$SLACKWARE" "$UNION"
      fi

if [ "$SRC" = "truva" ]; then
         sinstall "$PKG" "$TRUVA" "$UNION"
      fi
   done
   
#    cp -a ./bundles/$i/rootfs/* "$UNION"
#    sh ./bundles/$i/doinst.sh "$UNION"
done

# ----------------------
mkdir -p  /home/moduller
cd $UNION
# make squashfs images
for i in $(ls -1 | sort); do
   mksquashfs $i /home/moduller/$i.sb -comp xz -Xbcj x86 -b 512k
done

echo islem Tamamlandı ->> `date`

